[workspace]

resolver = "2"

members = [
    "crates/*",
]

[workspace.dependencies]
html5ever = "0.35"
anyhow = "1"
rcdom = { package = "markup5ever_rcdom", version = "0.35" }
blitz-dom = "0.1.0-rc.1"
blitz-html = "0.1.0-rc.1"

# servo deps
# script = { git = "https://github.com/minghuaw/servo.git", branch = "exp/parallel-mainthread" }
# layout = { git = "https://github.com/minghuaw/servo.git", branch = "exp/parallel-mainthread" }

# script = { path = "../servo/components/script" }
# script_bindings = { path = "../servo/components/script_bindings" }
# layout = { path = "../servo/components/layout" }
