[package]
name = "mini-servo"
version = "0.1.0"
edition = "2024"

[dependencies]
html5ever.workspace = true
anyhow.workspace = true
rcdom.workspace = true

# script.workspace = true
# script_bindings.workspace = true
# layout.workspace = true